brown_food/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin


urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'brown_food.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
                       url(r'^',include('core.urls',namespace='core')),
                       url(r'^admin/',include(admin.site.urls)),
)

core/urls.py
__author__ = 'wanyama'

from django.conf.urls import patterns,url
from core.views import *
from django.contrib.staticfiles.urls import static

urlpatterns = patterns('',
                       url(r'^$',home,name='home'),
                       url(r'^register/$',register,name='register'),
                       url(r'^cart/$',cart,name='cart'),
                       #url(r'^add_to_cart/$',add_to_cart,name='add_to_cart'),
                       #url(r'^update_cart/(?P<menu_id>\d+)/(?P<quantity>\d+)/$',update_cart,name='update_cart'),
                       url(r'^remove_from_cart/$',remove_from_cart,name='remove_from_cart'),
                       url(r'^order/$',order,name='order'),
                       url(r'^process_checkout/$',process_checkout,name='process_checkout'),
                       url(r'^checkout/$',checkout,name='checkout'),
                       url(r'^payment',payment,name='payment'),
                       url(r'^about_us/$',about_us,name='about_us'),
                       url(r'^menus/(?P<pk>[0-9]+)/$',MenuDetail.as_view(),name='menu-detail'),
                       url(r'^how-it-works/$',how_it_works,name='how-it-works'),
                       url(r'^menu/$',menu,name='menu'),
                       url(r'^login/$',login_customer,name='login'),
                       url(r'^logout/$',logout_customer,name='logout-customer'),
                       url(r'^process-order/$',process_order,name='process-order'),
                       url(r'^order-summary/$',order_summary,name='order-summary'),
                       url(r'^view-account/(?P<pk>\d+)/$',ViewAccount.as_view(),name='my-account'),
                       url(r'^edit-account/(?P<pk>\d+)/$',EditAccount.as_view(),name='edit-account'),
                       #url(r'^delivery_charged/$',delivery_charged,name='delivery_charged'),
                       url(r'^deposit/$',deposit,name='deposit'),
                       url(r'^process-deposit/$',process_deposit,name='process-deposit'),
                       url(r'^self-collect/$',self_collect,name='self-collect'),
                       url(r'^postpaid-payment/$',postpiad_payment,name='postpaid-payment'),
                       url(r'^add_to_cart/$',add_to_cart,name='add-to-cart'),
)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/forms.py
__author__ = 'wanyama'

from django.contrib.auth.forms import UserCreationForm,UserChangeForm
from django.contrib.auth.models import User
from django.forms import TextInput,EmailInput
from django import forms
from models import BillingDetails,Customer

class RegistrationForm(UserCreationForm):
    class Meta:
        model = Customer
        fields = ('username','first_name','last_name','email','password1','password2')
        widgets = {
            'username': TextInput(attrs={'class': 'form-control', 'placeholder': 'Username'}),
            'last_name': TextInput(attrs={'class': 'form-control', 'placeholder': 'Surname'}),
            'first_name': TextInput(attrs={'class': 'form-control', 'placeholder': 'First name'}),
            'email': EmailInput(attrs={'class': 'form-control', 'placeholder': 'Email'}),
            'password1':TextInput(attrs={'class':'form-control','placeholder': 'Password'}),
            'password2':TextInput(attrs={'class': 'form-control','placeholder': 'Repeat Password'}),
        }

class CustomerForm(forms.ModelForm):
    class Meta:
        model = Customer

class CustomerChangeForm(forms.ModelForm):

    class Meta:
        model = Customer
        fields = ('email','first_name','last_name','address_line1','address_line2',)
        widgets = {
            'email': TextInput(),
        }


class CustomerCreationForm(forms.ModelForm):
    password1 = forms.CharField(label='Password',widget=forms.PasswordInput)
    password2 = forms.CharField(label='Password Confirmation',widget=forms.PasswordInput)

    class Meta:
        model = Customer
        fields = ('email','address_line1','address_line2')

    def clean_password2(self):
        password1 = self.clanead_data.get('password1')
        password2 = self.cleaned_data.get('password2')
        if password1 and password2 and password1!=password2:
            raise forms.ValidationError("Passwords dont match")
        return password2

    def save(self,commit=True):
        customer = super(CustomerCreationForm,self).save(commit=False)
        customer.set_password(self.cleaned_data["password1"])
        if commit:
            customer.save()
        return customer

class PasswordResetRequestForm(forms.Form):
    email = forms.CharField(label=("Email"),max_length=200)

core/views.py
from django.shortcuts import render,redirect
from .models import CartItem,MenuItem,BillingDetails, Customer,PesaPal,Cart as CartModel
from django.views.generic import *
from django.core.exceptions import ObjectDoesNotExist
from cart import Cart
import json
from django.http import HttpResponse,HttpResponseRedirect
from django.contrib.auth import login,logout,authenticate
import urllib
import time
import datetime
from django.conf import settings
import pesapal
import requests
from forms import CustomerChangeForm,PasswordResetRequestForm
from django.core.urlresolvers import reverse

# Create your views here.

def login_customer(request):
    email = password = next_url = state = ''
    if request.GET:
        next_url = request.GET.get('next')
    if request.POST:
        next_url = request.POST.get('next')
        email = request.POST.get('email')
        password = request.POST.get('password')
        user = authenticate(email=email,password=password)
        if user is not None:
            if user.is_active:
                login(request, user)
                if next_url:
                    return HttpResponseRedirect(next_url)
                else:
                    return redirect('core:home')
            else:
                state = "Your account is not active"
        else:
            state = "Your email and password do not match"
    return render(request, 'core/login.html', {'state': state, 'email': email, 'password': password, 'next': next_url, })

def logout_customer(request):
    logout(request)
    return redirect('core:home')

def register(request):
    if request.POST:
        email = request.POST.get('email')
        password = request.POST.get('password1')
        password2 = request.POST.get('password2')
        customer = Customer()
        customer.email = email
        customer.password = password
        customer.save()
    return render(request,'core/login.html')

def home(request):
    return render(request,'core/home.html')

def about_us(request):
    return render(request,'core/about-us.html')

def signup(request):
    if request.method == 'POST':
        name = request.POST.get('name')

    return render(request,'core/checkout.html')

def cart(request):
    return render(request,'core/cart.html',{
        'cart':Cart(request)
    })

def update_cart(request):
    pass

def process_checkout(request):
    if request.method=="POST":
      if 'processed-checkout' in request.POST:
        cart = Cart(request)
        first_name = request.POST.get('first_name')
        last_name = request.POST.get('last_name')
        email = request.POST.get('email')
        address1 = request.POST.get('add1')
        address2= request.POST.get('add2')
        phone1 = request.POST.get('phone1')
        phone2 = request.POST.get('phone2')
        billing_details = cart.cart.billing_details
        if not billing_details:
            billing_details = BillingDetails()
        billing_details.address1 = address1
        billing_details.address2 = address2
        billing_details.phone1 = phone1
        billing_details.phone2 = phone2
        billing_details.save()
        client = pesapal.PesaPal("Au93fiwr5A/NhPZqesxbjVNDqzFBdMI+","d00fVQICYG8f/3kxueNRKQkfXnk=",False)
        total_cost = cart.grand_total()
        request_data = {
            'FirstName':first_name,
            'LastName':last_name,
            'Email':email,
            'Amount':str(total_cost),
            'Description':'Buying food from Brown foods',
            'Type':'MERCHANT',
            'Reference': str(datetime.datetime.now()),
            'Currency':'UGX',
        }
        post_params = {
            'oauth_callback': 'http://brown.co.ug/process-order'
        }
        pesapal_request = client.postDirectOrder(post_params, request_data)
        return render(request,'core/payment.html',{
            'iframe_url':pesapal_request.to_url(),
        })
      if 'postpaid' in request.POST:
          return render(request,'core/postpaid.html')

def payment(request):
    return render(request,'core/payment.html')

def checkout(request):
    if request.method=='POST':
        delivery_date = request.POST.get('delivery-date')
        if delivery_date:
             billing_details = BillingDetails()
             billing_details.delivery_date= delivery_date
             billing_details.save()
             session_cart = Cart(request)
             session_cart.cart.billing_details = billing_details
             session_cart.cart.save()
        if request.POST.get('self_collects',False):
           sess_cart = Cart(request)
           sess_cart.cart.self_collect = True

    return render(request,'core/checkout.html',{
        'cart':Cart(request),
    })

def add_to_cart(request):
    if request.POST:
        quantity = request.POST.get('quantity')
        pk = request.POST.get('menu_id')
        menu_item = MenuItem.objects.get(id=pk)
        cart = Cart(request)
        cart.add(menu_item,menu_item.unit_price,quantity)
        state=" %s has been added to cart" % menu_item
        request.session['state']=state
        return redirect('core:order')

def remove_from_cart(request):
    menu_id = request.POST.get('menu_id')
    menu_item = MenuItem.objects.get(id=menu_id)
    cart = Cart(request)
    cart.remove(menu_item)
    data = {'success':'true'}
    return HttpResponse(json.dumps(data),content_type="application/json")

def my_account(request):
    return render(request,'core/my_account.html')

def order_summary(request):
    orderList = CartModel.objects.all()
    context = {
        'orderList':orderList,
    }
    return render(request,'core/order_summary.html',context)



def process_order(request):
    '''
    Handle the callback from PesaPal
    '''
    sess_cart = Cart(request)
    tracking_id = request.GET.get('pesapal_transaction_tracking_id', '')
    reference = request.GET.get('pesapal_merchant_reference', '')
    if tracking_id and reference:
        params = {
            'pesapal_merchant_reference': reference,
            'pesapal_transaction_tracking_id': tracking_id
        }
        client = pesapal.PesaPal("Au93fiwr5A/NhPZqesxbjVNDqzFBdMI+","d00fVQICYG8f/3kxueNRKQkfXnk=",False)
        pesapal_request = client.queryPaymentStatus(params)
        url = pesapal_request.to_url()
        print url
        pesapal_response = requests.get(url)
        pesapal_response_data = pesapal_response.text
        pesapal_status = pesapal_response_data.split("=")[1]

        if pesapal_status == 'COMPLETED':
            state="Transaction was successful"
            sess_cart.cart.checked_out = True
            sess_cart.cart.save()
        else:
            state = "Transaction is %s" % pesapal_status

        p_ref = PesaPal(tracking_id=tracking_id,reference=reference,status=pesapal_status,cart=cart)
        p_ref.save()

    return render(request,'core/process-order.html',{
        'state':state,
    })

class MenuList(ListView):
    model = MenuItem
    template_name = 'core/order.html'

class MenuDetail(DetailView):
    model = MenuItem
    template_name = 'core/product-detail.html'

def how_it_works(request):
    return render(request,'core/how-it-works.html')

def menu(request):
    menu_items = MenuItem.objects.filter(menu_type='M')
    sliced_menu = menu_items[:9]
    last_item = menu_items[9:]
    side_dishes = MenuItem.objects.filter(menu_type='S')
    context = {'menu_items':sliced_menu,'side_dishes':side_dishes,'last_item':last_item}
    return render(request,'core/menu.html',context)

def order(request):

    cart = Cart(request)
    menu_items = MenuItem.objects.filter(menu_type='M')
    side_dishes = MenuItem.objects.filter(menu_type='S')
    context = {'menu_items':menu_items,'side_dishes':side_dishes,'cart':cart,}
    return render(request,'core/order.html',context)

class EditAccount(UpdateView):
    model = Customer
    form_class = CustomerChangeForm
    template_name = 'core/edit-account.html'

    def get_success_url(self):
        return reverse('core:my-account',args=(self.object.id,))

class ViewAccount(DetailView):
    model = Customer
    template_name = 'core/my_account.html'

def deposit(request):
    if request.POST:
        amount = request.POST.get('amount')
        customer = request.user
        client = pesapal.PesaPal("Au93fiwr5A/NhPZqesxbjVNDqzFBdMI+","d00fVQICYG8f/3kxueNRKQkfXnk=",False)
        if customer.first_name:
            first_name = customer.first_name
        if customer.last_name :
            last_name = customer.last_name

        request_data = {
            'FirstName':first_name,
            'LastName':last_name,
            'Email':customer.email,
            'Amount':amount,
            'Description':'Deposit for postpaid customer at Brown Foods',
            'Type':'MERCHANT',
            'Reference': str(datetime.datetime.now()),
            'Currency':'UGX',
        }
        post_params = {
            'oauth_callback': 'http://brown.co.ug/process-deposit/?amount=%s'%(str(amount))
        }
        pesapal_request = client.postDirectOrder(post_params, request_data)
        return render(request,'core/payment.html',{
            'iframe_url':pesapal_request.to_url(),
        })
    return render(request,'core/deposit.html')

def self_collect(request):
    return render(request,'core/order.html')

def postpiad_payment(request):
    if request.method=='POST':
        sess_cart = Cart(request)
        state='You need to login in your account'
        if request.user:
            customer = request.user
        if customer:
            if customer.balance-sess_cart.grand_total()<0:
                state="You have insufficient balance to complete this transaction"
            elif customer.balance-sess_cart.grand_total()>=0:
                state= "Your payment is successful"
        context = {'state':state}
    return render(request,'core/postpaid.html',context)

def process_deposit(request):
    '''
    Handle the callback from PesaPal
    '''

core/templates/core/base.html
{% include 'core/components/page_head_tags.html' %}
<div class="brown-food-container">
<nav class="navbar navbar-custom ">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a href="{% url 'core:home' %}"><img src="/static/core/img/brown_logo.png"> </a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><a href="{%url 'core:menu' %}">Menu</a></li>
        <!--<li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">One more separated link</a></li>
          </ul>
        </li>-->
          <li><a href="{%url 'core:order' %}">Order</a> </li>
          <li><a href="{%url 'core:how-it-works'%}">How it works</a> </li>
          <li><a href="{% url 'core:about_us'%}">About Us</a> </li>
          <!--<li><a href="{% url 'core:cart' %}">Cart</a> </li>-->
          <!--<li><a href="{% url 'core:order-summary' %}">Order Summary</a></li>-->
      </ul>
      <ul class="nav navbar-nav navbar-right">
          <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">My Account <span class="caret"></span></a>
              <ul class="dropdown-menu">
                  {% if user.is_authenticated %}
                  {% if user.is_postpaid %}
                  <li><a href="{% url 'core:deposit' %}">Deposit</a> </li> {% endif %}
                  <li><a href="{% url 'core:edit-account' user.id %}">Edit Details</a> </li>
                  <li><a href="{% url 'core:my-account' user.id %}">View Account</a> </li>
                  <li><a href="{% url 'core:logout-customer' %}">Logout</a> </li>
                  {% else %}
                  <li><a href="{% url 'core:login' %}">Login</a> </li>
                  <li><a href="{% url 'core:register'%}">Register</a> </li>
                  {% endif %}
              </ul>
          </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
    {% block slider %} {% endblock %}
</nav>

    {% if state %}
     <div class="alert alert-success" role="alert">
       {{state}}
     </div>
    {% endif %}
   <div class="brown-food-container pb40">
       {% block content %}
       {% endblock %}
   </div>

    <!--footer area are start-->
    <footer class="footer pb40">
        <div class="navbar-custom brown-food-container text-center">
            <div class="row">
                <div class="col-md-12 col-sm-12">
                Brown Foods Agency : <span>Sales Agent for Takumi Foods Ltd</span>
                </div>
            </div>
            <div class="row">
                <div class="col-md-12 col-sm-12">
                    Copyright &copy; 2016. All rights reserved
                </div>
            </div>
        </div>
    </footer>
    <!-- footer area stop -->

</div>
</div>
{% include 'core/components/page_foot_tags.html' %}
</body>

</html>

core/templates/core/customer_info.html
{% extends 'core/base.html' %}

core/templates/core/edit-account.html
{% extends 'core/base.html' %}
{% block content %}
    <div class="account-area">
    <div class="container">
        <div class="row">
            <div class="col-sm-6 col-xs-12">
                <form action="{% url 'core:edit-account' object.id %}" class="login-side" method="post">
                    {%csrf_token%}
              <div class="login-reg">
                <h3>Update Account</h3>
                  <div class="form-group">
                    <label class="control-label">Email</label>
                    <input type="text" class="form-control" placeholder="First Name" value="{{object.email}}" name="email">
                </div>
                <div class="form-group">
                    <label class="control-label">First Name</label>
                    <input type="text" class="form-control" placeholder="First Name" value="{{object.first_name}}" name="first_name">
                </div>
                <div class="form-group">
                    <label class="control-label">Last Name</label>
                    <input type="text" class="form-control" placeholder="Last Name" value="{{object.last_name}}" name="last_name">
                </div>
                  <div class="form-group">
                    <label class="control-label">Address 1</label>
                    <input type="text" class="form-control" placeholder="Address Line 1" value="{{object.address_line1}}" name="address_line1">
                </div>
                  <div class="form-group">
                    <label class="control-label">Address 2</label>
                    <input type="text" class="form-control" placeholder="Address Line 2" value="{{object.address_line2}}" name="address_line2">
                </div>
                  <div class="form-group">
                    <label class="control-label">Phone 1</label>
                    <input type="text" class="form-control" placeholder="Address Line 2" value="{{object.address_line2}}" name="address_line2">
                </div>

                </div>
                <div class="frm-action">
                    <div class="input-box tci-box">
                        <input type="submit" value="Update" name="processed-checkout" class="in-btn">
                    </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

core/templates/core/login.html
{% extends 'core/base.html' %}
{% block title %} Login {% endblock %}
{% block content %}
 <!-- Account Area Start -->
    <div class="account-area pb60 pt60">
    <div class="container">
        <div class="row">
            <div class="col-sm-6 col-xs-12">
                <form action="{% url 'core:login' %}" class="login-side" method="post">
                    {%csrf_token%}
                    {% if next %}
                    <input type="hidden" name="next" value="{{next}}"/>
                    {% endif %}
              <div class="login-reg">
                <h3>Login</h3>
                <div class="form-group">
                    <label class="control-label">E-Mail</label>
                    <input type="text" class="form-control" placeholder="E-Mail" value="" name="email">
                </div>
                <div class="form-group">
                    <label class="control-label">Password</label>
                    <input type="password" class="form-control" placeholder="Password" value="" name="password">
                </div>
                </div>
                <div class="frm-action">
                    <div class="input-box tci-box">
                        <input type="submit" value="Login" name="processed-checkout" class="in-btn">
                    </div>
                 <span>
                     <input class="remr" type="checkbox"> Remember me
                 </span>
                <a href="#" class="forgotten forg">Forgotten Password</a>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
    <!-- Account Area End -->

{% endblock %}

core/templates/core/order.html
{% extends 'core/base.html' %}
{% block title %}Order {% endblock %}
{% block content %}
{% block headers %}
<style>
    label {
    font-size :14px;
	font-weight: bold;
	float: left;
	padding-left:25px;
}
input[type="checkbox"] {
  width: 13px;
  height: 13px;
  padding-left: 25px;
  margin:0;
  vertical-align: bottom;
  position: relative;
  top: -1px;
  *overflow: hidden;
}
</style>
{% endblock %}
{% load core_extras %}
        <!--<pre> {% filter force_escape %} {% debug %} {% endfilter %} </pre>-->
   <div class="row ">
        <div class="8 col-sm-8 col-xs-12">
                      {% for item in menu_items %}
                      <div class="row">
                          <div class="col-md-3 col-sm-3">
                              <div class="pd-img">
                                  <a class="venobox" data-gall="myGallery" href=""><img src="{{item.image.url}}" alt=""></a>
                              </div>
                          </div>
                          <form action="{% url 'core:add-to-cart' %}" method="post">{% csrf_token %}
                             <div class="col-md-5 col-sm-5">
                                <div class="pd-content">
                                  <div class="order-title">
                                        <h3>{{item}}</h3>
                                   </div>
                                    <div class="sm-price">
                                        UGX {{item.unit_price|split}}<span>000</span>
                                    </div>
                                </div>
                          </div>
                              <div class="btn-add">
                          <div class="col-md-2 col-sm-2">
                               <input type="number" class="qty-btn" min="1" value="0" name="quantity" id="qty_{{item.id}}"/>
                              <input hidden="true" value="{{item.id}}" name="menu_id"/>
                          </div>
                          <div class="col-md-2 col-sm-2">
                              <input type="submit" class="btn btn-default" value="Add"/>
                          </div>
                              </div>
                          </form>

                          </div>
                      {% endfor %}
                         <br><br>
                      {% for side_dish in side_dishes %}
                      <form action="{% url 'core:add-to-cart' %}" method="post">{% csrf_token %}
                      <div class="row">
                          <div class="col-md-8 col-sm-8">

                                <div class="pd-content">
                                  <div class="order-title">
                                        <h3>{{side_dish}}</h3>
                                   </div>
                                    <div class="sm-price">
                                        UGX {{side_dish.unit_price|split}}<span>000</span>
                                    </div>
                                </div>
                          </div>
                              <div class="btn-add">
                          <div class="col-md-2 col-sm-2">
                               <input type="number" class="qty-btn" min="1" value="0" name="quantity" id="qty_{{side_dish.id}}"/>
                          </div>
                                  <!--
                          <div class="col-md-2 col-sm-2 ">
                              <a class="btn btn-default" onclick="cartAction('{{side_dish.id}}')">Add to Cart</a>
                          </div> -->
                                  <input hidden="true" name="menu_id" value="{{side_dish.id}}"/>
                                  <div class="col-md-2 col-sm-2">
                                      <input class="btn btn-default" type="submit" value="Add"/>
                                  </div>
                              </div>
                      </div> </form> <br><br>
                      {% endfor %}
                  </div>
        <div class="col-md-4 col-sm-4 col-xs-12">
                       <div class="total-aside">
                        <aside>
                             <div class="single-widget my-cart">
                                 <div class="whdget-title text-centered">
                                     <h2>Your Cart</h2>
                                 </div>
                                <div class="total-top-rated">
                                    <!-- Add Delivery Date -->
                                    <form method="post" action="{% url 'core:checkout' %}">{%csrf_token%}
                                        <div class="Zebra_DatePicker_Icon_Wrapper">
                                        <label>Delivery Date:</label>
                                        <input id="datepickers" name="delivery-date" type="text" class="date-wrapper"/>
                                    </div>
                                    <ul>

                                        {% for item in cart %}
                                        <li class="row ">
                                            <span class="quantity">{{item.quantity}}</span>
                                            <span class="itemName">{{item.menu_item}}</span>
                                            <span class="price">{{item.unit_price}}</span>
                                        </li>
                                        {% endfor %}
                                        <li class="row">
                                               <div class="itemName">Sub Total:</div>
                                               <div class="price">{{cart.summary}}</div><br>
                                               <div class="itemName">Delivery Fee:</div>
                                               <div class="price">{{cart.delivery_fee}}</div><br>
                                                <label>Self Collection <input type="checkbox" name="self_collects" id="collects"></label>
                                        </li>
                                        <li class="row">
                                            <span class="itemName">Grand Total:</span>
                                            <span class="price">{{cart.grand_total}}</span>
                                        </li>
                                     </ul>
                                    <div class="input-box">
                                        <input type="submit" class="in-btn" value="Checkout"/>
                                    </div>
                                    </form>
                                </div>
                             </div>
                            <div class="row">
                                <div class="col-md-2 offset-md-3">
                                </div>
                                <div class="col-md-8">
                                    <p>We may decline orders that exceed our capacity.</p>
                                </div>
                            </div>
                         </aside>
                        </div>
                     </div>
       </div>
<script>
  $( function() {
    $( "#datepicker" ).datepicker();
  } );
  </script>

{% endblock %}

core/templates/core/payment.html
{% extends 'core/base.html' %}
{% block content %}
<div class="cart-area pt60 pb60">
<div class="container">
    <div class="row">
        <div class="col-md-8">
            <h3>Payment</h3>
           <iframe src="{{iframe_url}}" width="100%" height="620px" scrolling="auto" frameBorder="0"> <p>Unable to load the payment page</p></iframe>
        </div>
    </div>
</div> </div>

{% endblock %}

core/templates/core/postpaid.html
{% extends 'core/base.html' %}
{% block content %}
       <!-- start of postpaid -->

                          <form method="post" action="{% url 'core:postpaid-payment' %}">

                                <div class="frm-action cc-area">
                                    <div class="input-box tci-box">
                                        <input type="submit" class="in-btn" name="processed-checkout" value="Buy">
                                    </div>
                            </div>
                          </div>
                        </div> <!-- End of Postpaid --></form>
{% endblock %}

core/templates/core/process-order.html
{% extends 'core/base.html' %}
{% block content %}
<div class="row">

</div>
{% endblock %}

core/templates/core/success.html
{% extends "core/base.html" %}
{% block content %}
    <p>Your payment has been successfuly processed. Thank you.</p>
{% endblock %}